# Introduction to PyTorch

## PyTorch is a deep learning framework. It has a set of classes and functions to implement deep learning easily.

In [1]:
# Importing
import torch

In [5]:
# Has a bunch of "numpy like" functions
my_tensor = torch.Tensor([[0, 1, 2], [0, 1, 2], [0, 1, 2]])
zeros_tensor = torch.zeros([3, 3])
ones_tensor = torch.ones([3, 3])
rand_tensor = torch.rand([3, 3])

print("my_tensor:\n%s\nzeros_tensor:\n%s\nones_tensor:\n%s\nrand_tensor:\n%s\n" 
      % (my_tensor, zeros_tensor, ones_tensor, rand_tensor))

my_tensor:
tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])
zeros_tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones_tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
rand_tensor:
tensor([[0.3164, 0.0906, 0.2209],
        [0.1492, 0.1779, 0.1458],
        [0.7434, 0.8140, 0.7034]])



In [7]:
# You get their shape
my_tensor_shape = my_tensor.size()
zeros_tensor_shape = zeros_tensor.size()
ones_tensor_shape = ones_tensor.size()
rand_tensor_shape = rand_tensor.size()
print("my_tensor shape: %s\nzeros_tensor shape: %s\nones_tensor shape: %s\nrand_tensor shape: %s\n" 
      % (my_tensor_shape, zeros_tensor_shape, ones_tensor_shape, rand_tensor_shape))

my_tensor shape: torch.Size([3, 3])
zeros_tensor shape: torch.Size([3, 3])
ones_tensor shape: torch.Size([3, 3])
rand_tensor shape: torch.Size([3, 3])



In [8]:
# And reshape them
my_tensor = my_tensor.view(9, 1)
zeros_tensor = zeros_tensor.view(1, 9)
ones_tensor = ones_tensor.view(9,)
rand_tensor = rand_tensor.view(9, 1)

my_tensor_shape = my_tensor.size()
zeros_tensor_shape = zeros_tensor.size()
ones_tensor_shape = ones_tensor.size()
rand_tensor_shape = rand_tensor.size()

print("my_tensor shape: %s\nzeros_tensor shape: %s\nones_tensor shape: %s\nrand_tensor shape: %s\n" 
      % (my_tensor_shape, zeros_tensor_shape, ones_tensor_shape, rand_tensor_shape))

my_tensor shape: torch.Size([9, 1])
zeros_tensor shape: torch.Size([1, 9])
ones_tensor shape: torch.Size([9])
rand_tensor shape: torch.Size([9, 1])



In [9]:
# But the real benefit of PyTorch is the neural network library
import torch.nn as nn

In [13]:
# It has various neural network layers
in_neurons, out_neurons = 8, 16
dense1 = nn.Linear(in_neurons, out_neurons)
print("Dense Layer:", dense1)

in_channels, out_channels = 32, 16
kernel_size = (3, 3)
strides, padding = 1, 1
conv1 = nn.Conv2d(in_channels, out_channels, kernel_size, strides, padding)
print("Conv layer:", conv1)

pool_size = (2, 2)
pool_stride = 2
maxpool1 = nn.MaxPool2d(pool_size, pool_stride)
print("MaxPool layer:", maxpool1)

Dense Layer: Linear(in_features=8, out_features=16, bias=True)
Conv layer: Conv2d(32, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
MaxPool layer: MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)


In [19]:
# And activations
tensor = torch.Tensor([1, 1, 1])
sigmoid = nn.Sigmoid()
relu = nn.ReLU()
softmax = nn.Softmax(dim = -1) # Have to specify dimension for this one (-1 indicates let it choose)
tanh = nn.Tanh()

print("Sigmoid Num: %s\nReLU Num: %s\nSoftmax Num: %s\nTanh Num: %s\n" 
      %(sigmoid(tensor), relu(tensor), softmax(tensor), tanh(tensor)))

Sigmoid Num: tensor([0.7311, 0.7311, 0.7311])
ReLU Num: tensor([1., 1., 1.])
Softmax Num: tensor([0.3333, 0.3333, 0.3333])
Tanh Num: tensor([0.7616, 0.7616, 0.7616])



In [21]:
# Loss functions (known as "criterion")
categorical_crossentropy = nn.CrossEntropyLoss()
binary_crossentropy = nn.BCELoss() # See the utility in action when we make our own neural networks

## Let's see how we can use these functions to implement a neural network!