# Numpy Tutorial

<div>
<img src="https://raw.githubusercontent.com/raunak-sood2003/Python-and-Machine-Learning-Club/master/Images/numpy.png" width="500"/>
</div>


## Numpy is a Python library used for array and matrix manipulation. It has many benefits over traditional Python lists.

  ### --> Provides multiple useful matrix operations
  ### --> Much less memory than Python lists
  ### --> You can specify the data type

In [1]:
# Importing the numpy library
import numpy as np

In [2]:
# Array creation
dim_x, dim_y = 3, 3 # Set the dimensions of the array

zeros = np.zeros([dim_x, dim_y]) # Array full of zeros
ones = np.ones([dim_x, dim_y]) # Array full of ones
rand = np.random.randn(dim_x, dim_y) # Array full of random floats
my_array = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]]) # Custom array
quick_array1 = np.arange(0, 9) # Creates array of values between 0 and n-1
quick_array2 = np.linspace(0, 8, 9) # Creates evenly split array [start, stop, split]

print("Zeros:\n %s\n\nOnes:\n %s\n\nRandom:\n %s\n\nMy Array:\n %s\n\nQuick Array 1:\n %s\n\nQuick Array 2:\n %s"  
      % (zeros, ones, rand, my_array, quick_array1, quick_array2))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random:
 [[ 1.35367716 -1.67614524  0.95676566]
 [ 1.2142571   0.74634566 -0.52450135]
 [-1.12819857  0.80862755 -0.10456017]]

My Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Quick Array 1:
 [0 1 2 3 4 5 6 7 8]

Quick Array 2:
 [0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [3]:
# Finding shape and reshaping arrays

zeros_shape = zeros.shape
ones_shape = ones.shape
rand_shape = rand.shape
my_array_shape = my_array.shape
quick_array1_shape = quick_array1.shape
quick_array2_shape = quick_array2.shape
# Notice how shape doesn't require parenthesis...what kind of data type is shape?

print("zeros_shape: %s\nones_shape: %s\nrand_shape: %s\nmy_array_shape: %s\nquick_array1_shape: %s\nquick_array2_shape: %s" 
      % (zeros_shape, ones_shape, rand_shape, my_array_shape, quick_array1_shape, quick_array2_shape))

zeros_shape: (3, 3)
ones_shape: (3, 3)
rand_shape: (3, 3)
my_array_shape: (3, 3)
quick_array1_shape: (9,)
quick_array2_shape: (9,)


In [4]:
# What is the (9,)?
# It's called a rank 1 array, meaning that the array could be treated as (9, 1) or (1, 9) depending on the situation

#Reshaping arrays
dim_x = 4
dim_y = 4
cool_array = np.zeros([dim_x, dim_y])
cool_array_reshaped = cool_array.reshape(-1, dim_x*dim_y) #This is called flattening the array
rank1_cool = cool_array.reshape(dim_x*dim_y,) 

print("cool_array shape: %s\ncool_array_reshaped shape: %s\nrank1_cool shape: %s\n" 
      % (cool_array.shape, cool_array_reshaped.shape, rank1_cool.shape))

cool_array shape: (4, 4)
cool_array_reshaped shape: (1, 16)
rank1_cool shape: (16,)



In [5]:
# Getting the size of an array
cool_array_size = cool_array.size
rank1_cool_size = rank1_cool.size

print("cool_array size:", cool_array_size)
print("rank1_cool size", rank1_cool_size)

cool_array size: 16
rank1_cool size 16


In [6]:
# Array operations

arr1 = np.array([[0, 1], 
                 [2, 3]])

arr2 = np.array([[1, 2], 
                 [2, 3]])

added_arr = arr1 + arr2
sub_arr = arr1 - arr2
element_wise_arr = arr1 * arr2
div_arr = arr1 / arr2
mat_mul_arr = np.matmul(arr1, arr2)
transposed_arr1 = arr1.T

print("Adding:\n%s\n\nSubtracting:\n %s\n\nElement-wise mult:\n %s\n\nDivision:\n %s\n\nMatrix mult:\n %s\nTransposed Arr1:\n %s" 
      % (added_arr, sub_arr, element_wise_arr, div_arr, mat_mul_arr, transposed_arr1))

Adding:
[[1 3]
 [4 6]]

Subtracting:
 [[-1 -1]
 [ 0  0]]

Element-wise mult:
 [[0 2]
 [4 9]]

Division:
 [[0.  0.5]
 [1.  1. ]]

Matrix mult:
 [[ 2  3]
 [ 8 13]]
Transposed Arr1:
 [[0 2]
 [1 3]]


In [7]:
# Vectors and Tensors
# Vocab: Vector refers to a matrix that is either a row or column e.g (1, n) or (n, 1)
# Vocab: Tensor is an important DL word meaning multi-dimensional matrix

vector = np.random.randn(3, 1)
tensor = np.random.randn(3, 3, 3)

print("Vector:\n", vector)
print("Tensor:\n", tensor) # Notice the number of brackets (hard to visualize 3d on a screen)

Vector:
 [[0.08078238]
 [0.50933729]
 [0.51059987]]
Tensor:
 [[[-0.29831685  0.08999135 -0.12953911]
  [-0.29138058 -2.74618891 -0.6953872 ]
  [-0.42526406 -0.84685342 -0.6502572 ]]

 [[-0.02341423  0.47586026 -0.10714244]
  [ 1.42824721 -1.04201558  0.58758762]
  [ 0.69572734  1.49173693 -0.45213675]]

 [[-0.17865579  0.5103712  -0.2817568 ]
  [ 0.79323557 -0.48974862  0.99206512]
  [ 1.63345458 -1.0697359  -1.02644155]]]


In [8]:
# Sclicing

# We know how to slice 1D Python lists
ls = [1, 2, 3, 4, 5]
first_three = ls[:3] # Gets first three elements
print(first_three)

[1, 2, 3]


In [9]:
# ...And 2D Python lists
mat = [[0, 1, 2],
     [3, 4, 5],
     [6, 7, 8]]
first_row = mat[0][:]
print(first_row)

[0, 1, 2]


In [10]:
# ...And any dimensional Python list
mat_3D =  [[[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]],
          [[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]],
          [[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]]]
# This is a (3 x 3 x 3) tensor, like a rubix cube

first_slice = mat_3D[0][:][:]
print(first_slice) # Kinda have to imagine it stacked

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [11]:
# Numpy works the same way
n = 3
vector = np.random.randn(n, 1)
matrix = np.random.randn(n, n)
tensor = np.random.randn(n, n, n)

first_three_vector = vector[:3]
first_row_matrix = matrix[0][:]
first_slice_tensor = tensor[0][:][:]

print("First three numbers of vector:\n%s\nFirst row of matrix:\n%s\nFirst slice of tensor:\n%s\n" 
      % (first_three_vector, first_row_matrix, first_slice_tensor))

First three numbers of vector:
[[-0.44003042]
 [-1.51174639]
 [ 0.16020351]]
First row of matrix:
[-0.62797352 -0.97004791 -1.04568711]
First slice of tensor:
[[-1.45935618  0.90934649  0.11832525]
 [-0.49981458  0.28478863  0.54774432]
 [ 0.12636605 -1.78464152  0.73706047]]



In [12]:
# Notice how the first three numbers came as a two dimensional array even though it could be written as an (n, 1) vector
# We can fix this by "squeezing the matrix"

squeezed_vector = np.squeeze(first_three_vector) # Makes it as low dimensional as possible
print(squeezed_vector)

[-0.44003042 -1.51174639  0.16020351]


In [13]:
# Max, mins and there indexes
# Memorize these, very important

fun_array = np.array([5, 4, 6, 3, 9, 10, 4])

maxNum = np.amax(fun_array)
minNum = np.amin(fun_array)
maxIndex = np.argmax(fun_array)
minIndex = np.amin(fun_array)

print("Max Num: %s\nMin Num: %s\nMax Num Index: %s\nMin Num Index: %s\n" 
      % (maxNum, minNum, maxIndex, minIndex))

Max Num: 10
Min Num: 3
Max Num Index: 5
Min Num Index: 3



# Review 

## All important numpy instance variables

### array.shape
### array.size

## Important numpy functions

### np.zeros([dim_X = ..., dim_y = ...])
### np.ones([dim_X = ..., dim_y = ...])
### np.random.randn(dim_X = ..., dim_y = ...)
### np.array([iterable])
### np.arange(start, stop, step)
### np.linspace(start, stop, num)
### np.amax(array)
### np.amin(array)
### np.argmax(array)
### np.argmin(array)

## Other stuff

### All operations (add, sub, matmul, element_wise_mult, division, transpose)
### Vocab: vector, matrix, tensor
### Slicing 1D, 2D and higher dimensional numpy arrays [:, :,  ...]
### Squeezing arrays: array.squeeze()
### Reshaping arrays: array.reshape(n, n, ...)

# Thanks for listening!!

<div>
<img src="https://raw.githubusercontent.com/raunak-sood2003/Python-and-Machine-Learning-Club/master/Images/fun_img.png" width="500"/>
</div>